config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :users, only: [:index, :create]
  resources :leagues do
    scope module: :leagues do
      resources :games do
        scope module: :games do
          resources :players
        end
      end
    end
  end
  resources :games, only: [:index]
  resources :participants
  resources :players, only: [:index]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/dashboard", to: "users#show", as: "dashboard"
  get "/new-account", to: "users#new", as: "new_user"
  get "/not-found", to: "pages#not_found", as: "not_found"
end

app/models/participant.rb
class Participant < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name

  validates_uniqueness_of :first_name , scope: :last_name
  belongs_to :user
  has_many :players


  def global_attendance(league)
    (player_count / league.game_count.to_f) * 100
  end

  def global_score(league)
    players.sum(&:score) / player_count
  end

  def global_win_or_placed(league)
    (top_three_count / player_count.to_f) * 100
  end

  def longest_streak(league)
    eligible_players = players.joins(:game).where("games.season_id IN (?)", league.season_ids).pluck(:finishing_place)
    eligible_players.chunk do |place|
      place == 1 || place == 2 || place == 3
    end.map { |_, x| x.size }.max
  end

  def player_count
    players.count
  end

  def top_three_count
    players.where(finishing_place: [1, 2, 3]).count
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def index
    @participants = current_user.participants
  end

  def show
    @participant = Participant.find(params[:id])
  end

  def new
    @participant = Participant.new
  end

  def create
    set_redirect
    @participant = current_user.participants.new(participant_params!)
    if @participant.save
      flash[:success] = "New Player Created!"
      redirect_to session[:redirect]
    else
      flash[:danger] = "Something went wrong!"
      render :new
    end
  end

  def edit
    @participant = Participant.find(params[:id])
  end

  def update
    @participant = Participant.find(params[:id])
    if @participant.update(participant_params!)
      flash[:success] = "Player Updated!"
      redirect_to @participant
    else
      flash[:danger] = "Something went wrong!"
      render :edit
    end
  end

  private

  def participant_params!
    params.require(:participant).permit(:first_name, :last_name)
  end
end

app/views/participants/_form_fields.html.erb
  <div class="input-field">
    <%= f.text_field :first_name %>
    <%= f.label :first_name, "First Name" %>
  </div>
  <div class="input-field">
    <%= f.text_field :last_name %>
    <%= f.label :last_name, "Last Name" %>
  </div>

app/views/participants/edit.html.erb
<div class="row">
  <div class="col l4 offset-l4 s12">
    <h5>Edit Player</h5>
    <%= form_for @participant do |f| %>
      <%= render partial: "form_fields", locals: { f: f } %>
      <%= f.submit "Update Player!" %>
    <% end %>
  </div>
</div>

app/views/participants/index.html.erb
<% @participants.each do |participant| %>
  <% present(participant) do |p| %>
    <div class="participant-<%= participant.id %>">
      <p><%= "#{p.full_name} - #{p.player_count}" %></p>
      <p><%= link_to "edit player", edit_participant_path(p) %></p>
    </div>
    <hr>
<% end %>
<% end %>

app/views/participants/new.html.erb
<div class="row">
  <div class="col l4 offset-l4 s12">
    <h5>Create A New Player</h5>
    <%= form_for @participant do |f| %>
    <%= render partial: "form_fields", locals: { f: f } %>
    <%= f.submit "Create Player!", class: "btn btn-poker" %>
    <% end %>
  </div>
</div>

app/views/participants/show.html.erb
<% present(@participant) do |participant| %>
  <h2><%= participant.full_name %></h2>
  <%= link_to "edit player", edit_participant_path(@participant) %>
<% end %>