config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :users, only: [:index, :create]
  resources :leagues do
    scope module: :leagues do
      resources :games do
        scope module: :games do
          resources :players
        end
      end
    end
  end
  resources :games, only: [:index]
  resources :participants
  resources :players, only: [:index]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/dashboard", to: "users#show", as: "dashboard"
  get "/new-account", to: "users#new", as: "new_user"
  get "/not-found", to: "pages#not_found", as: "not_found"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :email
  validates_uniqueness_of :email, case_sensitive: false
  validates_presence_of :password_digest
  has_many :leagues
  has_many :participants

  def unfinished_participants(game)
    ids = participants.joins(:players).where(players: { game_id: game.id }).pluck(:id)
    participants.where.not(id: ids)
  end

  def no_leagues
    leagues.count == 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def show
    @user = current_user
    @leagues = @user.leagues
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params!)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account Created!"
      redirect_to dashboard_path
    else
      flash[:danger] = "Something went wrong!"
      render :new
    end
  end

  private

  def user_params!
    params.require(:user).permit(:email, :password)
  end
end

app/views/users/new.html.erb
<div class="row">
  <div class="col l4 offset-l4 s12">
    <h5>Create A New Account</h5>
    <%= form_for @user do |f| %>
      <%= render partial: "shared/form_fields", locals: { f: f } %>
      <%= f.submit "Create Account", class: "btn btn-poker" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= link_to "Create League", new_league_path, class: "btn btn-poker" %>
<div class="row">
  <% if @user.no_leagues %>
    <h3>You have no leagues. Create one to get started.</h3>
  <% else %>
    <% @leagues.each do |league| %>
      <%= render partial: "shared/league_card", locals: { league: league } %>
    <% end %>
  <% end %>
</div>