config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  resources :users, only: [:index, :create]
  resources :leagues do
    scope module: :leagues do
      resources :games do
        scope module: :games do
          resources :players
        end
      end
    end
  end
  resources :games, only: [:index]
  resources :participants
  resources :players, only: [:index]

  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "logout"
  get "/dashboard", to: "users#show", as: "dashboard"
  get "/new-account", to: "users#new", as: "new_user"
  get "/not-found", to: "pages#not_found", as: "not_found"
end

app/views/shared/_finished_players.html.erb
<div class="scored-players">
  <ul class="collection with-header">
    <li class="collection-header">
      <h4>Scored Players</h4>
    </li>
    <% @game.finished_players.each do |player| %>
      <% present(player.participant) do |participant| %>
        <li class="collection-item">
          <span class="badge poker-gold"><%= player.finishing_place %></span>
          <p><%= participant.full_name %></p>
          <p class="score">Score: <%= player.score %></p>
          <% if scorable %>
            <div>
              <%= link_to "[Edit]", edit_league_game_player_path(league, @game, player), class: "close-link" %>
              <span class="tooltipped" data-tooltip="are you really sure you want to delete this?!">
                <%= button_to "[Delete]", league_game_player_path(league, @game, player), method: :delete, class: "close-button delete"  %>
              </span>
            </div>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/shared/_form_fields.html.erb
<div class="input-field">
  <%= f.text_field :email, autofocus: true %>
  <%= f.label :email, "E-Mail Address" %>
</div>
<div class="input-field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

app/views/shared/_league_card.html.erb
<div class="col l6 xl4 s12 <%= league.slug %>">
  <div class="card">
    <div class="card-content">
      <div class="delete-div tooltipped" data-position="bottom" data-tooltip="are you sure? this will delete everything associated with this league">
        <%= button_to "clear", { controller: :leagues, action: "destroy", id: league.slug }, method: :delete, form_class: "material-icons delete-icon delete-league-#{league.slug}" %>
      </div>
      <span class="card-title"><%= league.name %></span>
      <div class="<%= league.slug %>-actions league-actions">
        <%= link_to "view league details", league_path(league), class: "action" %>
        <%= link_to "edit league name", edit_league_path(league), class: "action" %>
        <%= link_to "schedule game", new_league_game_path(league), class: "action" %>
      </div>
      <ul>
        <li><p><strong>Unscored Games: </strong> <%= link_to league.unscored_games.count, league_games_path(league, type: "unscored") %></p></li>
        <li><p><strong># of games: </strong> 16</p></li>
        <li><p><strong># of seasons: </strong> 2</p></li>
      </ul>
    </div>
    <div class="card-tabs">
      <ul class="tabs tabs-fixed-width">
        <li class="tab"><a href="#<%= "#{league.slug}-players" %>">Players</a></li>
        <li class="tab"><a href="#<%= "#{league.slug}-games" %>">Games</a></li>
        <li class="tab"><a href="#<%= "#{league.slug}-seasons" %>">Seasons</a></li>
      </ul>
    </div>
    <div class="card-content grey lighten-4">
      <div id="<%= "#{league.slug}-players" %>">
        <ul>
          <li><p><strong>Best: </strong>Michael Cassano</p></li>
          <li><p><strong>Avg/game: </strong>8</p></li>
        </ul>
      </div>
      <div id="<%= "#{league.slug}-games" %>">one two three four five<br />one two three four five<br />one two three four five<br />one two three four five<br />one two three four five<br />one two three four five<br />one two three four five<br /></div>
      <div id="<%= "#{league.slug}-seasons" %>">Test 3</div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "New Player", new_participant_path, class: "nav-link" %></li>
  <li><%= link_to "All Players", participants_path, class: "nav-link" %></li>
  <li class="divider"></li>
  <li><a class="nav-link" href="#!">one</a></li>
  <li><a class="nav-link" href="#!">two</a></li>
  <li class="divider"></li>
  <li><a class="nav-link" href="#!">three</a></li>
</ul>

<nav class="grey lighten-4">
  <div class="nav-wrapper container">
    <!-- <a href="#!" class="brand-logo"><span>POKER</span>RANK</a> -->
    <%= link_to root_path, class: "brand-logo" do %>
      <span>POKER</span>RANK
    <% end %>
    <a href="#" data-activates="mobile-demo" class="nav-link button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li><a class="nav-link dropdown-button" href="#!" data-activates="dropdown1">Dropdown<i class="material-icons dropdown-button right">arrow_drop_down</i></a></li>
        <li><%= link_to "Dashboard", dashboard_path, class: "nav-link" %></li>
        <li><%= link_to "Log Out", logout_path, class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "New Account", new_user_path, class: "nav-link" %></li>
        <li><%= link_to "Log In", login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <% if current_user %>
        <li><%= link_to "New Player", new_participant_path, class: "nav-link" %></li>
        <li><%= link_to "All Players", participants_path, class: "nav-link" %></li>
        <li class="divider"></li>
        <li><%= link_to "Dashboard", dashboard_path, class: "nav-link" %></li>
        <li><%= link_to "Log Out", logout_path, class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "New Account", new_user_path, class: "nav-link" %></li>
        <li><%= link_to "Log In", login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>